services:
  goimgtool-dev:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DISPLAY=host.docker.internal:0.0
    command: go run ./cmd/main.go