FROM golang:1.24.6-alpine


RUN apk add --no-cache \
    gcc musl-dev libwebp-dev mesa-dev \
    libx11-dev libxrandr-dev libxinerama-dev \
    libxcursor-dev libxi-dev

WORKDIR /app


COPY go.mod go.sum ./
RUN go mod download


CMD ["sleep", "infinity"]
